"""add data

Revision ID: 28b789eaa14c
Revises: 1298b56ec76e
Create Date: 2023-01-11 19:02:53.487073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28b789eaa14c'
down_revision = '1298b56ec76e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
